// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByJjvKIPiZV4qyvLbg9YGUXMbS4oKn-eE',
    appId: '1:1098222833011:web:b2b9f4dfed60c930264906',
    messagingSenderId: '1098222833011',
    projectId: 'fruit-app-b4fad',
    authDomain: 'fruit-app-b4fad.firebaseapp.com',
    storageBucket: 'fruit-app-b4fad.firebasestorage.app',
    measurementId: 'G-MCWE9MNY3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbmPXO3nSyfGzkWRZ6DTVv-vWkkrTn8bo',
    appId: '1:1098222833011:android:a4c0b473cdd4bfd1264906',
    messagingSenderId: '1098222833011',
    projectId: 'fruit-app-b4fad',
    storageBucket: 'fruit-app-b4fad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4QbmQROog5p3FxOTeKr3HD5uAhBU3hLE',
    appId: '1:1098222833011:ios:c2644751d5453f25264906',
    messagingSenderId: '1098222833011',
    projectId: 'fruit-app-b4fad',
    storageBucket: 'fruit-app-b4fad.firebasestorage.app',
    iosBundleId: 'com.example.fruitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4QbmQROog5p3FxOTeKr3HD5uAhBU3hLE',
    appId: '1:1098222833011:ios:c2644751d5453f25264906',
    messagingSenderId: '1098222833011',
    projectId: 'fruit-app-b4fad',
    storageBucket: 'fruit-app-b4fad.firebasestorage.app',
    iosBundleId: 'com.example.fruitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByJjvKIPiZV4qyvLbg9YGUXMbS4oKn-eE',
    appId: '1:1098222833011:web:ada6d78167dcc96c264906',
    messagingSenderId: '1098222833011',
    projectId: 'fruit-app-b4fad',
    authDomain: 'fruit-app-b4fad.firebaseapp.com',
    storageBucket: 'fruit-app-b4fad.firebasestorage.app',
    measurementId: 'G-0HVMP71R7Z',
  );
}
